### ISSUE TITLE
Default CSS: Add PMLC Version Info

### ISSUE THREAD

**Issue by tajmone** [pml-lang/converter#12]
Pleas inject into default CSS styles the version number of the `pmlc` tool that generated them, i.e. within the stylesheets commented header, at the beginning.

This might be a safer practice, in case end users are manually modifying copies of these CSS files for substituting the default CSS generated by `pmlc`. Having `pmlc` version info might warn end users of possible changes in class names or the HTML template structure.

**Comment by pml-lang** [comment]
Good point!
It's done.
Example: [PML_CSS_files.zip](https://github.com/pml-lang/converter/files/6180040/PML_CSS_files.zip)

**Comment by tajmone** [comment]
Great! Thanks.

I wanted to experiment a bit with SASS templates, a sort of "Stylesheet Factory" that could auto-generate PML CSS via different color schemes, etc — mostly to start and get a feel of the underlying HTML template structure, and how it can be styled via CSS.

Definitely, CSS and HTML templates customization is a feature most end users love in any documentation generator, especially HTML templating, which would allow to add custom nav bars and use PML for websites or HTML books, not just single-page docs.

**Comment by pml-lang** [comment]
> auto-generate PML CSS via different color schemes

Excellent idea. Color is always a matter of personal preferences (and branding sometimes). We should make it easy for users to chose _their_ preferred colors, styling, and layouts.

> CSS and HTML templates customization is a feature most end users love in any documentation generator

True 100%.
Too much choice is not always good, but easy and flexible CSS and HTML customization is necessary.
Reminds me excellent advice I'm fond of:
"It should be easy to do simple things; possible to do complex things; and impossible, or at least difficult, to do wrong things."
[Joshua Bloch: Bumper-Sticker API Design](https://www.infoq.com/articles/API-Design-Joshua-Bloch/)

> use PML for websites or HTML books, not just single-page docs

Yes and yes.

**Comment by tajmone** [comment]
> Color is always a matter of personal preferences (and branding sometimes). 

But also a matter of web-accessibility, e.g. for the color blind (see:tajmone/Git-Buch_EN#15).

Any default HTML templates and stylesheets should meet as many triple As (AAA) as possible for web accessibility standards, IMO, and then end users are free to use whatever they want. Unfortunately, in the software industry, in general, we're not witnessing enough efforts in terms of accessibility in UI/GUI designs. Striving in a FOSS project to stick to those guidelines as much as possible, and being able to proudly publicize it in its website, would be a great way to promote awareness about accessibility issues. Furthermore, providing a web-accessible-ready product would be a strong incentive to its use.

https://www.w3.org/WAI/fundamentals/accessibility-intro/

**Comment by pml-lang** [comment]
Important point to consider. Well said.

Thanks for the link. Will read it thoughtfully, because I'm a noob when it comes to web accessibility.
