### ISSUE TITLE
Enable Discussions

### ISSUE THREAD

**Issue by tajmone** [pml-lang/converter#2]
Please enable Discussion for the repository, so that end user might freely discuss topics that don't directly affect the repo's development (e.g. the pros and cons of adding new features, comparisons to other syntaxes, etc.) and avoid polluting Issues (which should be reserved for practical maintenance).

**Comment by pml-lang** [comment]
Good idea. Done!

**Comment by pml-lang** [comment]
Thanks for the tip. I've enabled discussions.

Christian
