### ISSUE TITLE
PML Convert 1.3.0: GUI screen bug

### ISSUE THREAD

**Issue by celtic-coder** [pml-lang/converter#20]
### Step to reproduce:

Clicking in the GUI at the point indicated by the arrow, clears the screen:

![Clears-the-screen](https://user-images.githubusercontent.com/11787866/114273718-2756fb00-9a13-11eb-8d40-115b498f3571.png)

### Result:

This results in a blank screen with just the window title:

![Blank-Screen](https://user-images.githubusercontent.com/11787866/114273740-39389e00-9a13-11eb-8384-282c7f8b9072.png)

### Comment:

The black dot seems to be part of a background window mostly hidden by the main window. Clicking anywhere else on the thin border does not cause any problems. Just the black dot clears the screen.

Is this background window required for the GUI to function? In any case, the GUI has to be closed as there is nothing with which to interact.

**Comment by pml-lang** [comment]
This is actually a bug in the GUI framework used by PML (based on JavaFX). I have taken note of the bug, and I close this issue here because it's not directly related to PML. The bug should disappear as soon as it is fixed in a new version of the GUI framework.
