### ISSUE TITLE
Add Alternative Text for <img> tags

### ISSUE THREAD

**Issue by celtic-coder** [pml-lang/converter#21]
Hi Christian (@pml-lang),

I noticed that the online version of the manual was generated by PML 1.2.0 and that one of the differences from the current 1.3.0 version is that <img> tag has a closing "/" character.

As a further enhancement, in terms of [accessibility](https://github.com/pml-lang/converter/issues/12#issuecomment-805371389), it is recommended that each image has a [text alternative](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML#text_alternatives). Even in cases where there is no valid alternative, an [empty alt tag](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML#empty_alt_attributes) is still recommended.

In the PML Reference Manual, in the section for the [image node](https://www.pml-lang.dev/docs/reference_manual/index.html#node_image), there are attributes for captions, node title, etc. but nothing for alternative text. Should this be included? Could  `alt=""` be added as a default value for this attribute of the <img> tag?

Kind Regards,
Liam

**Comment by pml-lang** [comment]
The reason for not having a PML `alt` tag is that `alt` is specific to HTML.
The solution is to use an `html_alt` tag (e.g. `html_alt = "Delicious strawberries"`).
More information can be found in chapter [HTML Attributes](https://www.pml-lang.dev/docs/user_manual/index.html#HTML_attributes) of PML's user manual.

I have appended a note in the description of the `image` node, and added an `html_alt` attribute in the node's example. Thus it will be more clear in the next version of PML's reference manual.

In a future version PML could possibly auto-create an `html_alt` attribute (if it's not explicitly defined), based on the values of the `title` and `caption` attributes.

**Comment by celtic-coder** [comment]
Thanks for the clarification!

**Comment by pxml-lang** [comment]
Update:

The behavior has now been changed (in the new online version 1.4.0) and works as follows (excerpt from online [reference manual](https://www.pml-lang.dev/docs/reference_manual/index.html#node_image)):

> Note about the HTML 'alt' tag:
Attribute 'html_alt' can be used to add an explicit 'alt' attribute in the resulting HTML (see example).
If no explicit 'html_alt' is provided then the value of the 'title' attribute is used for the 'alt' attribute.
If no 'title' attribute is provided then the value of the 'caption' attribute is used.
