### ISSUE TITLE
Table of Contents entries cut off on mobile 

### ISSUE THREAD

**Issue by celtic-coder** [pml-lang/converter#22]
Hi Christian (@pml-lang),

I was checking the PML User Manual on my mobile phone and found that the Table of Contents was not appearing correctly. Several words were being cut-off as seen in the screenshots below.

To see this effect using Firefox on my desktop, I went into Developer Tools <F12> and selected the Responsive Design Mode icon over on the top-right of the panel:

![Responsive-Design-Mode](https://user-images.githubusercontent.com/11787866/114629928-62765a00-9cb1-11eb-9819-6323baacc2df.png)

The alternative method is to select the Web Developer option from the "burger" menu, which gives these options:

![Web-Developer-Menu](https://user-images.githubusercontent.com/11787866/114630008-8a65bd80-9cb1-11eb-8e10-4e2d37f50060.png)

In Responsive Design Mode, several Device Settings are available in the drop-down. For example:

- Galaxy S9/S9+
- iPhone 6/7/8
- Kindle Fire HDX Linux

Other device settings can be chosen by using the "Edit List..." option at the bottom of the drop-down.

The **Galaxy S9/S9+** view in Landscape mode gives this:

![Galaxy-S9-Landscape](https://user-images.githubusercontent.com/11787866/114630297-35767700-9cb2-11eb-85fb-6267dbd93c05.png)

The **iPhone 6/7/8**, again in Landscape mode, has a similar problem:

![iPhone-6-Landscape](https://user-images.githubusercontent.com/11787866/114630533-b766a000-9cb2-11eb-9ed9-da9a1d0a83dc.png)

I know little about responsive design or how the CSS, perhaps, might have an impact on the layout of the page. In any case, the default HTML / CSS might need to be reviewed for how the Table of Contents is displayed on various mobile platforms.

Kind Regards,
Liam

**Comment by pml-lang** [comment]
Thanks for the report.

I've tuned the CSS a bit to fix the bug. Here is the new CSS:

```
.pml-doc-left, .pml-doc-right {
    flex-grow: 1;
    flex-shrink: 1;
    width: 15%;

    background-color: #fafafa;
}

.pml-doc-text {
    flex-grow: 0;
    flex-shrink: 3;
    max-width: 800px;
}
```

This is how it looks now on Galaxy S9:
![GalaxyS9](https://user-images.githubusercontent.com/77769154/114665978-e2d7a200-9d27-11eb-8a9e-6a79bf40a725.png)

The right empty side is reserved for later when HTML chunks will be supported. The main TOC will then be displayed on the left, and the current chapter's sub-TOC on the right.

The fix will be included in the next PML version.
