### ISSUE TITLE
Div node ID not referenceable

### ISSUE THREAD

**Issue by coemgenuslcp** [pml-lang/converter#64]
In version `2.1.0 2021-09-09`, the following code
```
Body of text with a footnote here[sup
    [xref node_id="footnote1" text="1"]
].

[div id="footnote1" 1
    Footnote contents
]
```
yields the following error from the compiler.
```
Error      A node with id 'footnote1' does not exist.                                                                  
Code       [xref node_id="footnote1" text="1"]
```
The order of `[xref]` and `[div]` does not make a difference.

Possibly related to #58.

**Comment by pml-lang** [comment]
Since version 2 attributes must be enclosed in parenthesis (unless it's a node that cannot have child nodes).

Therefore this line:
```
[div id="footnote1" 1
```
... must be written as:
```
[div (id="footnote1") 1
```
